version: '3'
services:
  producer:
    depends_on:
      - kafka
    build:
      context: ./producer
    networks:
      - election-network
    volumes:
      - ./Data:/Data

  consumer:
    depends_on:
      - kafka
    build:
      context: ./consumer
    networks:
      - election-network

  kafka:
    image: spotify/kafka
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    container_name: kafka
    expose:
    - "9092"
    - "2181"
    environment:
    - ADVERTISED_HOST=192.168.0.103
    - ADVERTISED_PORT=9092
    - AUTO_CREATE_TOPICS=true
    networks:
      - election-network

  postgres:
    image: "postgres:11"
    container_name: "postgres"
    environment:
    - POSTGRES_USER=consumer
    - POSTGRES_DB=Elections
    - POSTGRES_PASSWORD=goto@Postgres1
    ports:
    - "5432:5432"
    networks:
    - election-network
    volumes:
    - ./Postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  election-network:
    external:
      name: election-network



