version: '3'
services:
  kafka:
    image: spotify/kafka
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    container_name: kafka
    expose:
    - "9092"
    - "2181"
    environment:
    - ADVERTISED_HOST=$LOCAL_IP
    - ADVERTISED_PORT=9092
    - AUTO_CREATE_TOPICS=true
    - DELETE_TOPIC_ENABLE=true
    networks:
      - election-network

  postgres:
    image: "postgres:11"
    container_name: "postgres"
    environment:
    - POSTGRES_USER=consumer
    - POSTGRES_DB=Elections
    - POSTGRES_PASSWORD=goto@Postgres1
    ports:
    - "5432:5432"
    networks:
    - election-network
    volumes:
    - ./Postgres:/var/lib/postgresql/data

  jupyter-local:
    container_name: "jupyter"
    image: jupyter/all-spark-notebook
    ports:
    - 8888:8888
    - 4040:4040
    - 4041:4041
    volumes:
    - ./notebooks:/home/jovyan/work

  producer:
    container_name: producer
    depends_on:
    - kafka
    build:
      context: ./producer
    networks:
    - election-network
    volumes:
    - ./Data:/usr/bin/app/Data
    - ./config:/usr/bin/app/config

  consumer:
    container_name: consumer
    depends_on:
    - kafka
    - postgres
    build:
      context: ./consumer
    networks:
    - election-network
    volumes:
    - ./config:/usr/bin/app/config

  aggregator:
    container_name: aggregator
    depends_on:
    - postgres
    build:
      context: ./aggregator
    networks:
    - election-network
    volumes:
    - ./config:/usr/bin/app/config

networks:
  election-network:
    external:
      name: election-network









