version: '3'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    hostname: kafka
    container_name: kafka
    expose:
      - "9092"
      - "2181"
    environment:
      - ADVERTISED_HOST=192.168.0.103
      - ADVERTISED_PORT=9092
      - AUTO_CREATE_TOPICS=true


